[features]
seeds = false
skip-lint = false

[programs.localnet]
y100go_bubblegum_badge = "B4xBYJcwRj1C722z7yTNog9aNfrKG2MvAxejkaJHK3xz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
